### ISSUE TITLE
Support expr-.. (double dot) for string concatenation 

### ISSUE THREAD

**Issue by kutsan** [Vimjas/vint#365]
See:

- https://vimhelp.org/eval.txt.html#expr-..
- https://github.com/vim/vim/commit/0f248b006c2574abc00c9aa7886d8f33620eb822

```vim
let g:foo = 'bar' .. 'baz'
let g:foo = 'bar' . 'baz'
```

Since they are the same, vint shouldn't produce an error such as:

```
unexpected token: . (see vim-jp/vim-vimlparser)
```

**Comment by kutsan** [comment]
The features is implemented by vimlparser as seen here: https://github.com/vim-jp/vim-vimlparser/issues/173

**Comment by mvanderkamp** [comment]
I believe this is already fixed? I did a `pip install` on a clone of the repo and no longer saw this error.

**Comment by kutsan** [comment]
I'm still getting this error.

![image](https://user-images.githubusercontent.com/10108377/108654736-5accdd00-74da-11eb-8eb6-b04665626894.png)

**Comment by blueyed** [comment]
Appears to be fixed in master (b577a623e9279d44eb3dc81e6817c8eec25add63; and released as v0.4a2).
To install it use `--pre` with pip.

**Comment by kutsan** [comment]
Hmm, I should have tried building from master. Thanks @blueyed.
